services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Appserver.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Appserver.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
